
name: run-notebooks

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute notebooks
        run: |
          mkdir -p executed_notebooks
          jupyter nbconvert --to notebook --execute notebooks/*.ipynb --output-dir=executed_notebooks
      - name: Upload executed notebooks
        uses: actions/upload-artifact@v4
        with:
          name: executed_notebooks
          path: executed_notebooks
